supermarket_prices:
  outputs:
    dev:
      type: duckdb
      path: /data/dbt.duckdb
      filesystems:
        - fs: s3
          anon: false
          key: "{{ env_var('MINIO_ROOT_USER') }}"
          secret: "{{ env_var('MINIO_ROOT_PASSWORD') }}"
          client_kwargs:
            endpoint_url: "http://minio:9000"
  target: dev