name: Schedule Build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Create env file
      run: |
        touch .env
        echo POSTGRES_USER=airflow >> .env
        echo POSTGRES_PASSWORD=airflow >> .env
        echo POSTGRES_DB=airflow >> .env
        echo MINIO_ROOT_USER=minio123 >> .env
        echo MINIO_ROOT_PASSWORD=minio123 >> .env
        echo MINIO_BUCKET_NAME='prices-bucket' >> .env
        echo DBT_PROFILES_DIR='/usr/app/dbt' >> .env
        echo DBT_TARGET=dev >> .env
        echo WRITE_TO_AWS=TRUE >> .env
        echo AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} >> .env
        echo AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} >> .env
        echo S3_BUCKET=$S3_BUCKET >> .env
        
    - name: Run docker compose
      uses: hoverkraft-tech/compose-action@v2.0.1
      with:
        compose-file: "./docker-compose.yaml"
        up-flags: "--detach --build"

    - name: Wait for 10 seconds for containers to spin up
      run: sleep 10
      
    - name: Unpause DAG
      run: docker exec -it scheduler airflow dags unpause price_etl

    - name: Run DAG
      run: docker exec -it scheduler airflow dags test price_etl