name: Schedule Build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Create env file
      run: |
        touch .env
        echo POSTGRES_USER=airflow >> .env
        echo POSTGRES_PASSWORD=airflow >> .env
        echo POSTGRES_DB=airflow >> .env
        echo MINIO_ROOT_USER=minio123 >> .env
        echo MINIO_ROOT_PASSWORD=minio123 >> .env
        echo MINIO_BUCKET_NAME='prices-bucket' >> .env
        echo DBT_PROFILES_DIR='/usr/app/dbt' >> .env
        echo DBT_TARGET=dev >> .env
        echo WRITE_TO_AWS=TRUE >> .env
        echo AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} >> .env
        echo AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} >> .env
        echo S3_BUCKET=${{ secrets.S3_BUCKET }} >> .env
        
    - name: Create dir and grant access
      run: |
        mkdir airflow/logs app/data
        chmod -R 777 airflow/logs/ dbt/supermarket_prices/ app/data/
      
    - name: Run docker compose
      run: |
        docker compose up --detach --build
        sleep 10

    - name: Unpause DAG
      run: docker exec -t scheduler airflow dags unpause price_etl
      
    - name: Run DAG
      run: |
        docker exec -t scheduler airflow dags test price_etl